apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvappsdata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/appsdata/nginx-app" # path on local host