apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-app
  namespace: nginx-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: "pvc-nginx-app"